# Generated by Django 5.1.3 on 2024-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otplist',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
