# Generated by Django 5.1.3 on 2024-11-23 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otplist_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplist',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='otplist',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
