# Generated by Django 5.2 on 2025-04-17 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(through='chats.UserRoom', through_fields=('room', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
